export const HOME_ICON = require("../asset/image/home-dark.png")
export const NOTE_ICON = require("../asset/image/notes-dark.png")
export const PLAN_ICON = require("../asset/image/plans-dark.png")
export const MOMENT_ICON = require("../asset/image/moments-dark.png")
export const SETTINGS_ICON = require("../asset/image/settings-dark.png")
export const BACK_ICON = require("../asset/image/back-dark.png")
export const LOGOUT_ICON = require("../asset/image/logout-dark.png")
export const ADD_ICON = require('../asset/image/add-dark.png')
export const ADD_DISABLE_ICON = require("../asset/image/add-disable.png")
export const DELETE_ICON = require('../asset/image/delete-dark.png')
export const DELETE_ICON_COLOR = require('../asset/image/delete-color.png')
export const CLEAR_ICON = require('../asset/image/clear-dark.png')

export const SAVE_ENABLE = require("../asset/image/check-mark-enable.png")
export const SAVE_DISABLE = require("../asset/image/check-mark-disable.png")

export const NO_AVATAR_IMAGE = require("../asset/image/user.png")
export const SUCCESS_IMAGE = require("../asset/image/success.png")
export const BRAIN_IMAGE = require("../asset/image/brain.png")
export const NO_PHOTO_IMAGE = require("../asset/image/image-dark.png")
export const COMPLETE_TASK_IMAGE = require("../asset/image/complete.png")
export const INCOMPLETE_TASK_IMAGE = require("../asset/image/incomplete.png")
export const EMPTY_IMAGE = require("../asset/image/empty-dark.png")
